name: Deploy APEX and DB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show SQLcl Version
        run: |
          "C:\sqlcl\bin\sql.exe" -v

      - name: Run schema_baselines.sql (DB Objects)
        env:
          DB_CONNECT: ${{ secrets.DB_CONNECT_STRING }}
          DB_USER: ${{ secrets.DB_DEPLOY_USER }}
          DB_PASS: ${{ secrets.DB_DEPLOY_PASSWORD }}
        run: |
          echo %DB_PASS% | "C:\sqlcl\bin\sql.exe" -s -L -thin %DB_USER%@%DB_CONNECT% @apex\db\schema_baselines.sql

      - name: Run import_all.sql (APEX App + DB items)
        env:
          DB_CONNECT: ${{ secrets.DB_CONNECT_STRING }}
          DB_USER: ${{ secrets.DB_DEPLOY_USER }}
          DB_PASS: ${{ secrets.DB_DEPLOY_PASSWORD }}
        run: |
          echo %DB_PASS% | "C:\sqlcl\bin\sql.exe" -s -L -thin %DB_USER%@%DB_CONNECT% @scripts\import_app_102